final List<Map<String, dynamic>> destinations = [
  {
    "imageUrl": "assets/images/intro_screen_mountain.png",
    "title": "Tranquil Books & Coffee",
    "description": "Coffee Shop · Cozy and quiet place for book lovers.",
    "price": "\$25",
    "rating": 4.5,
    "location": "123 Serenity Lane, Booktown",
    "openingHours": "8:00 AM - 10:00 PM",
    "type": "Coffee Shop",
  },
  {
    "imageUrl": "assets/images/intro_screen_mountain.png",
    "title": "The Craft House Cathedral",
    "description": "Gift Shop · Unique souvenirs and handmade crafts.",
    "price": "\$15",
    "rating": 4.8,
    "location": "456 Artisan Alley, Craftsville",
    "openingHours": "10:00 AM - 6:00 PM",
    "type": "Gift Shop",
  },
  {
    "imageUrl": "assets/images/intro_screen_mountain.png",
    "title": "Sunset Boulevard Bistro",
    "description": "Bistro · Enjoy meals with a beautiful sunset view.",
    "price": "\$40",
    "rating": 4.6,
    "location": "789 Sunset Blvd, Cityview",
    "openingHours": "12:00 PM - 10:00 PM",
    "type": "Bistro",
  },
  {
    "imageUrl": "assets/images/intro_screen_mountain.png",
    "title": "Mountain Majesty Resort",
    "description": "Resort · Rejuvenate in the lap of nature.",
    "price": "\$200",
    "rating": 4.9,
    "location": "123 Mountain Path, Highland",
    "openingHours": "24/7",
    "type": "Resort",
  },
  {
    "imageUrl": "assets/images/intro_screen_mountain.png",
    "title": "Seaside Paradise",
    "description": "Beach Resort · A perfect getaway with ocean views.",
    "price": "\$150",
    "rating": 4.7,
    "location": "321 Ocean Drive, Seaville",
    "openingHours": "6:00 AM - 12:00 AM",
    "type": "Beach Resort",
  },
];
