final List<Map<String, String>> tickets = [
  {
    "startDate": "Sep 20",
    "startTime": "09:50",
    "endDate": "Sep 21",
    "endTime": "15:38",
    "startLocation": "LON",
    "endLocation": "PAR",
    "totalDuration": "14h20m",
    "ticketType": "flight",
    "imagePath": "assets/images/flight_icon.png",
  },
  {
    "startDate": "Sep 25",
    "startTime": "08:00",
    "endDate": "Sep 25",
    "endTime": "16:30",
    "startLocation": "NYC",
    "endLocation": "BOS",
    "totalDuration": "8h30m",
    "ticketType": "train",
    "imagePath": "assets/images/train_icon.png",
  },
  {
    "startDate": "Sep 28",
    "startTime": "07:15",
    "endDate": "Sep 28",
    "endTime": "12:30",
    "startLocation": "DEL",
    "endLocation": "MUM",
    "totalDuration": "5h15m",
    "ticketType": "bus",
    "imagePath": "assets/images/bus_icon.png",
  },
];
